version: '3.4'

services:
  build:
    image: golang:latest
    entrypoint: /usr/src/clic/build.sh
    volumes:
      - .:/usr/src/clic
    working_dir: /usr/src/clic/src

  test:
    build: ./test
    command: npm test
    working_dir: /test
    volumes:
      - ./bin/linux-amd64/clic:/usr/local/bin/clic
      - ./test:/test
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SKIP_MOUNT_TESTS=true
