version: '3.4'

services:
  build:
    image: golang:latest
    command: /bin/sh -c "
      for GOOS in darwin linux; do
        for GOARCH in amd64; do
          export GOOS GOARCH;
          echo ----- Building $$GOOS $$GOARCH -----;
          CGO_ENABLED=0 go build -v -o ../bin/clic-$$GOOS-$$GOARCH;
        done;
      done;"
    volumes:
      - .:/usr/src/clic
    working_dir: /usr/src/clic/src

  test:
    build: ./test
    command: npm test
    working_dir: /test
    volumes:
      - ./bin/clic-linux-amd64:/usr/local/bin/clic
      - ./test:/test
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SKIP_MOUNT_TESTS=true
