version: '3'

services:
  build:
    image: golang:latest
    command: bash -c "go build *.go"
    working_dir: /usr/src/clic
    volumes:
      - .:/usr/src/clic
    environment:
      - GOOS=darwin
      - GOARCH=amd64